### ISSUE TITLE
'default': None not allowed for type=decimal

### ISSUE THREAD

**Issue by antoineL** [ShawnMilo/fixedwidth#19]
Simple test is to replace none_date with none_decimal in the current test suite (see attached source and the easier-to-read diff). This fails loudly:

> ERROR: test_basic (__main__.TestFixedWidth)
> 
> Traceback (most recent call last):
>   File "...\fixedwidth.git\fixedwidth\tests\fixedwidth_testNoneDecimal.py", line 150, in test_basic
>     fw_obj = FixedWidth(fw_config)
>   File "...\fixedwidth.git\fixedwidth\fixedwidth.py", line 134, in __init__
>     value['default'] = Decimal(value['default'])
> TypeError: conversion from NoneType to Decimal is not supported
> 

Since while reading (`_string_to_dict`) a field which is space-filled will also raise an exception if there is no default (`Decimal('')` is not accepted, this makes `decimal` awkward to deal with.

[fixedwidth_testNoneDecimal.zip](https://github.com/ShawnMilo/fixedwidth/files/1737235/fixedwidth_testNoneDecimal.zip)

**Comment by ShawnMilo** [comment]
@antoineL 

Thanks for all the help with this project recently -- especially answering community questions!

I don't spend time on this project very often -- I mostly write Go instead of Python these days, and haven't personally needed `fixedwidth` for years. Are you interested in becoming a maintainer?

**Comment by antoineL** [comment]
Thanks for the offer.
Fact is I am currently looking deeply with this class for a larger project I am working on, but I do not expect to use that code very often beyond it. Also I am not a regular Python programmer either. So I am not really in a different position from yours. I certainly will try to give a hand in the future if I can, but assuming the maintenance is not likely to end in a much better shape than with you.
So the offer made sense to me, but I am sorry I have to decline it.

**Comment by antoineL** [comment]
I believe antoineL/fixedwidth/52d379f8af35f6904bd622465ab407826f85eafd (branch none-decimal) should fix that particular issue.

**Comment by ShawnMilo** [comment]
Please create a PR for the fix and I'll review. Thanks!
