### ISSUE TITLE
new function "fw_from_dict"

### ISSUE THREAD

**Issue by ilmondovero** [ShawnMilo/fixedwidth#23]
can you implement a new function?

#current way
from fixedwidth.fixedwidth import FixedWidth
dict_01 = {"aaa": {"required": True,"type": "string","start_pos": 1,"end_pos": 5,"alignment": "left","padding": " "},"bbb": {"required": True,"type": "string","start_pos": 6,"end_pos": 10,"alignment": "left","padding": " "}}
dict_02 ={ "aaa" :"xxx","bbb":"yyy"}
fw_obj = FixedWidth(dict_01)
**fw_obj.update(aaa=dict_02.get("aaa",""),bbb=dict_02.get("bbb", "***"))**
print(fw_obj.line)

future way
from fixedwidth.fixedwidth import FixedWidth
dict_01 = {"aaa": {"required": True,"type": "string","start_pos": 1,"end_pos": 5,"alignment": "left","padding": " "},"bbb": {"required": True,"type": "string","start_pos": 6,"end_pos": 10,"alignment": "left","padding": " "}}
dict_02 ={ "aaa" :"xxx","bbb":"yyy"}
fw_obj = FixedWidth(dict_01)
**fw_obj.fw_from_dict(dict_02)**
print(fw_obj.line)

**Comment by ShawnMilo** [comment]
Thanks for the suggestion. The issue demonstrates that this can already be done in a simpler way. Simpler is better. Implementing this functionality means more code to maintain and test, without adding any value.
