### ISSUE TITLE
[Suggestion] Regenerate config when changes are made

### ISSUE THREAD

**Issue by muhammedabad** [ShawnMilo/fixedwidth#24]
@ShawnMilo First of all, thank you for this library - it has come to my rescue on a few projects I have worked on to date.

The project I'm currently working on is still in an early phase so the structure of my config is always changing.  What I do struggle with is having to change all indexes below the point where I make a change (such as adding a new field or changing `start_pos`,  `end_pos` or `length` of an existing field. Since the config is rather large, this is rather time consuming and could take a few attempts to finally get all start/end positions updated correctly.

The script below detects any incorrect positions within the config and adjusts them accordingly. Please feel free to add it in should you like to.

```python
"""
Author: @muhammedabad

Assuming all lengths are correct, this script takes a fixed-width config and recursively re-writes the start and
end positions when new fields are added to the config or existing lengths are modified.

"""

from fixedwidth.fixedwidth import FixedWidth

sample_config = {
    'field_one': {
        'required': True,
        'type': 'string',
        'start_pos': 1,
        'end_pos': 2,
        'alignment': 'right',
        'padding': '0',
        'length': 2,
    },

    'field_two': {
        'required': True,
        'type': 'string',
        'start_pos': 3,
        'end_pos': 6,
        'alignment': 'right',
        'padding': '0',
        'length': 4,
    },

    'field_three': {
        'required': True,
        'type': 'string',
        'start_pos': 7,
        'end_pos': 41,
        'alignment': 'left',
        'padding': ' ',
        'length': 35,
    }
}

start_pos = 0
end_pos = 0

for key in sample_config.keys():
    if not all([end_pos, start_pos]):
        start_pos = sample_config[key]['start_pos']
        end_pos = start_pos + sample_config[key]['length'] - 1

    else:
        start_pos = end_pos + 1
        end_pos = start_pos + sample_config[key]['length'] - 1

        sample_config[key]['start_pos'] = start_pos
        sample_config[key]['end_pos'] = end_pos

# Initialize the new config in a FW object which handles the validation.
fw_config = FixedWidth(config=sample_config)

# Use an online python prettifier like https://pythoniter.appspot.com/ and paste in the output from the line below
print(sample_config)

```

**Comment by ShawnMilo** [comment]
Hey @muhammedabad. So, if I understand correctly, you're _creating_ a new fixed-width spec as part of your project. That's something I've never heard of before -- all my experience is in having to use an existing (decades-old) fixed-width spec. Let me know if I'm misunderstanding your use case.

In general, this isn't something I think would be widely useful enough to add to the library (and then have to maintain, test, etc.), but it might be worth adding a helper scripts folder or something and putting it there. Although, as I said, if this only helps people who are defining the fixed-width format itself, then I'd be very surprised if anyone would need it. Are you designing a text-based protocol similar to the way Redis does it or something?

**Comment by muhammedabad** [comment]
> Hey @muhammedabad. So, if I understand correctly, you're creating a new fixed-width spec as part of your project. That's something I've never heard of before -- all my experience is in having to use an existing (decades-old) fixed-width spec. Let me know if I'm misunderstanding your use case.

I think you misunderstood, yes. Apologies if I was not clear enough in explaining the issue.

My script is solely to be used as a utility (or helper function as you mentioned it). In the case where a config has many fields and for some reason a change to a field in the middle of the config is required, such as a length change, one would have go through each field ***below*** the point where the change was made and adjust all the start and end positions of each field. I found this rather tiring - not to mention making further mistakes further down while changing all the start and end positions. The same would apply if one had to insert a new field in the middle of the config.

*NB.*  The only reason we had repeated changes to the config was due to the project being in a rather early phase where the structure of the fixed width file changed quite often until we were happy with it.

This script addresses that issue, allowing you to regenerate your config if you make a change. It's not a lacking feature on any part of the library - I hope it didn't come across that way.

Hope this helps.

**Comment by ShawnMilo** [comment]
Okay, I see. So you _are_ creating a new fixed-width spec. That's very unusual. Just out of curiosity, why would you need to _create_ a fixed-width spec these days?

If you want to create a PR with a `helper_scripts` folder I'll take a look at it.

**Comment by muhammedabad** [comment]
> Okay, I see. So you _are_ creating a new fixed-width spec. That's very unusual. Just out of curiosity, why would you need to _create_ a fixed-width spec these days?
> 
> If you want to create a PR with a `helper_scripts` folder I'll take a look at it.

It's actually a third-party we're working with, who have extended (like you mentioned) a decades-old, tried, trusted system. Simply put, they are just adding a few new fields but the things such as the order, length etc of the new fields kept changing during the planning phase. Each change required me as the integrating party to adjust my config as they made changes.

I'll create a PR with a helpers directory in the next few days.

**Comment by samarth222** [comment]
Shawn thank you very much for writing this. This is the best solution I have found on the internet to write production level fwfs.  This is still widely used in the bank world (mainly in the USA) especially when ordering data from credit bureaus such as TransUnion. Where you have to send your customer information to the bureau to get customers credit history/ alternative data. The fixed width format changes at every order since there are different fields you need to send every time along with the customer's basic information. Can you please point to an example where a fixed width file is written from a pandas dataframe using this module? We have quarterly orders to the bureau that contains 2 million plus rows and 120 plus columns. That would be very helpful.

**Comment by ShawnMilo** [comment]
Hi @samarth222. I'm glad you find it useful! Yes, it was actually created originally for working with US banks. I know nothing about Pandas, so I can't be helpful here. Also, this issue is over a year old and there hasn't been an update, so I'll close it now.
