### ISSUE TITLE
Could not import FixedWidth

### ISSUE THREAD

**Issue by rpzk** [ShawnMilo/fixedwidth#3]
fixedwidth import FixedWidth
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name FixedWidth

import fixedwidth
fixedwidth.__
fixedwidth.**class**(         fixedwidth.**format**(        fixedwidth.**new**(           fixedwidth.**repr**(
fixedwidth.**delattr**(       fixedwidth.**getattribute**(  fixedwidth.**package**        fixedwidth.**setattr**(
fixedwidth.**dict**           fixedwidth.**hash**(          fixedwidth.**path**           fixedwidth.**sizeof**(
fixedwidth.**doc**            fixedwidth.**init**(          fixedwidth.**reduce**(        fixedwidth.**str**(
fixedwidth.**file**           fixedwidth.**name**           fixedwidth.**reduce_ex**(     fixedwidth.**subclasshook**(

**Comment by ShawnMilo** [comment]
Sorry it took me so long to respond. Evidently, you currently have to do this:

`from fixedwidth.fixedwidth import FixedWidth`

I haven't maintained this code recently, so it could certainly use an overhaul. I wrote it years ago and haven't had much use for it in about five years. Plus, I mostly write Go now, so if anything I'd probably end up writing a Go version.

I am open to patches and other help, though!

**Comment by rpzk** [comment]
Thanks! I will give it a tryl!
Em 14 de jun de 2016 17:51, "Shawn Milochik" notifications@github.com
escreveu:

**Comment by rpzk** [comment]
It works!
Thanks a lot!
